
language: cpp

# safelist
branches:
  only:
  - master
  - stable
  - develop

compiler:
  - g++

jobs:
  include:
    - os: linux
    - os: osxs

install:
  - ./.travis/install.sh


script:
  - make -j
