os: 
 - linux
 - osx
 
language: cpp

# safelist
branches:
  only:
  - master
  - stable
  - develop

compiler:
  - g++

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo "MAC OSX"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo "LINUX"; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y build-essential cmake xorg-dev libgl1-mesa-dev libfreetype6-dev
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j
