os: linux
language: cpp

# safelist
branches:
  only:
  - master
  - stable
  - develop


compiler:
  - g++

jobs:
  include:
    - stage: build
      name: "Linux Build Debug"
      os: linux
      install:
        - bash .travis/installLinux.sh
        - bash .travis/prepareCmake.sh
      script:
        - cd build && make -j

    - stage: build
      name: "MacOS Build Debug"
      os: osx
      install:
        - bash .travis/prepareCmake.sh
      script:
        - cd build && make -j
