os: linux
language: cpp

compiler:
  - g++

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y build-essential cmake xorg-dev libgl1-mesa-dev libfreetype6-dev
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j
