os: linux
language: cpp

# safelist
branches:
  only:
  - master
  - stable
  - develop

stages:
  - build

compiler:
  - g++

jobs:
  include:
    - stage: build
      os: linux
      install:
        - bash .travis/installLinux.sh
        - bash .travis/prepareCmake.sh
      script:
        - make -j

    - stage: build
      os: osx
      install:
        - bash .travis/prepareCmake.sh
      script:
        - make -j

