language: cpp

compiler:
  - g++

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - build-essential
          - cmake
          - libgl1-mesa-dev
          - libfreetype6-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j

