######################################################################
# Automatically generated by qmake (2.01a) lun. oct. 8 12:08:19 2018
######################################################################

GLM_PATH  = glm

TEMPLATE = app
TARGET = run
DEPENDPATH += .
INCLUDEPATH += . $${GLM_PATH}
QT += opengl
LIBS += -lm -lGLEW

# Input
HEADERS += template.h shader.h
SOURCES += main.cpp template.cpp shader.cpp
