name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependancies
      run: sudo apt-get update -qq && sudo apt-get install -y build-essential cmake xorg-dev libgl1-mesa-dev libfreetype6-dev
    - name: configure cmake 
      run: mkdir build && cd build && cmake ..
    - name: compile
      run: cd build && cmake --build .
